- name: apt
  ansible.builtin.apt:
    name:
      - nginx
      - libnginx-mod-stream

- name: file
  ansible.builtin.file:
    path: /etc/nginx/stream.d
    state: directory
    mode: "0755"

- name: blockinfile
  ansible.builtin.blockinfile:
    dest: /etc/nginx/nginx.conf
    insertafter: EOF
    block: |
      stream {
          include /etc/nginx/stream.d/*.conf;
      }
  ignore_errors: true

- name: template
  ansible.builtin.template:
    src: ./files/lb/default.conf.j2
    dest: /etc/nginx/stream.d/default.conf
  ignore_errors: true

- name: shell
  ansible.builtin.shell: unlink /etc/nginx/sites-enabled/default
  ignore_errors: true

- name: service
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: true
  ignore_errors: true
