- name: apt
  ansible.builtin.apt:
    name:
      - nginx
      - libnginx-mod-stream

- name: blockinfile
  ansible.builtin.blockinfile:
    dest: /etc/nginx/nginx.conf
    insertafter: EOF
    block: |
      stream {
          upstream k8s-api {
              server {{ NODE_IP_1 }}:6443;
              server {{ NODE_IP_2 }}:6443;
              server {{ NODE_IP_3 }}:6443;
          }
          server {
              listen 6443;
              proxy_pass k8s-api;
          }
      }
  ignore_errors: true

- name: template
  ansible.builtin.template:
    src: ./files/lb/default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  ignore_errors: true

- name: shell
  ansible.builtin.shell: unlink /etc/nginx/sites-enabled/default
  ignore_errors: true

- name: service
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: true
  ignore_errors: true
