apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  # Explicit 'readOnly: false' applied to 'mountPath' causes perpetual out-out-sync
  # https://github.com/argoproj/argo-cd/issues/19038
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
spec:
  project: cluster-wide-apps
  source:
    chart: cilium
    repoURL: https://helm.cilium.io/
    targetRevision: 1.16.1
    helm:
      releaseName: cilium
      values: |
        kubeProxyReplacement: true
        socketLB:
          hostNamespaceOnly: true
        cni:
          exclusive: false
        k8sServiceHost: 192.168.11.110 # modify it if necessary
        k8sServicePort: 6443
        loadBalancer:
          algorithm: maglev
        hubble:
          enabled: true
          relay:
            enabled: true
          ui:
            enabled: true
          metrics:
            enabled:
            - dns:query;ignoreAAAA
            - drop
            - tcp
            - flow
            - icmp
            - http
            - port-distribution
            # # Enable additional labels for L7 flows
            # - "httpV2:sourceContext=workload-name|pod-name|reserved-identity;destinationContext=workload-name|pod-name|reserved-identity;labelsContext=source_namespace,destination_namespace,traffic_direction"
            # - "kafka:sourceContext=workload-name|pod-name|reserved-identity;destinationContext=workload-name|pod-name|reserved-identity;labelsContext=source_namespace,destination_namespace,traffic_direction"
            # enableOpenMetrics: true
            # serviceMonitor:
            #   enabled: true
            #   labels:
            #     release: prometheus
            # dashboards:
            #   enabled: true
            #   namespace: monitoring
        operator:
          prometheus:
            enabled: true
            serviceMonitor:
              enabled: true
              labels:
                release: prometheus
        prometheus:
          enabled: true
          serviceMonitor:
            enabled: true
            labels:
              release: prometheus

        # # service mesh. Gateway API Support: https://docs.cilium.io/en/stable/network/servicemesh/gateway-api/gateway-api/
        # nodePort:
        #   enabled: true
        # l7Proxy: true
        # gatewayAPI:
        #   enabled: true
        # # Cluster Mesh API Server Metrics: https://docs.cilium.io/en/stable/observability/metrics/#cluster-mesh-api-server-metrics
        # clustermesh:
        #   apiserver:
        #     metrics:
        #       enabled: true
        #       kvstoremesh:
        #         enabled: true
        #       etcd:
        #         enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
