apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  project: cluster-wide-apps
  source:
    chart: istio
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.16.5
    helm:
      releaseName: istio
      values: |
        config:
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
