# postgres-operator
# https://github.com/zalando/postgres-operator/tree/v1.10.1
- name: shell
  shell: |
    kubectl create namespace postgres-operator
    helm repo add postgres-operator-charts https://opensource.zalando.com/postgres-operator/charts/postgres-operator
    helm install postgres-operator postgres-operator-charts/postgres-operator --namespace=postgres-operator
    helm repo add postgres-operator-ui-charts https://opensource.zalando.com/postgres-operator/charts/postgres-operator-ui
    helm install postgres-operator-ui postgres-operator-ui-charts/postgres-operator-ui --namespace=postgres-operator

# postgres operator ui LB
- name: copy
  copy:
    src: ./files/cp/postgres-operator-ui-lb.yaml
    dest: /tmp/postgres-operator-ui-lb.yaml
    mode: "0644"
  ignore_errors: yes

- name: shell
  shell: kubectl apply -f /tmp/postgres-operator-ui-lb.yaml
