- name: apt
  ansible.builtin.apt:
    name:
      - haproxy
      - keepalived

- name: copy
  ansible.builtin.copy:
    src: ./files/redundant/wk/haproxy/haproxy.cfg
    dest: /etc/haproxy/
    mode: "0644"
  ignore_errors: true

- name: shell
  ansible.builtin.shell: echo "net.ipv4.ip_nonlocal_bind = 1" >> /etc/sysctl.conf

- name: shell
  ansible.builtin.shell: sysctl --system

- name: copy
  ansible.builtin.copy:
    src: "./files/redundant/wk/keepalived/keepalived_{{ inventory_hostname }}.conf"
    dest: /etc/keepalived/keepalived.conf
    mode: "0644"
  ignore_errors: true

- name: service
  ansible.builtin.service:
    name: keepalived
    state: restarted
    enabled: true
  ignore_errors: true

- name: service
  ansible.builtin.service:
    name: haproxy
    state: restarted
    enabled: true
  ignore_errors: true
