lb:
  hosts:
    k8s-lb-1:
      ansible_host: 192.168.11.110

cp:
  hosts:
    k8s-cp-1:
      ansible_host: 192.168.11.114

# cp_join:
#   hosts:
#     k8s-cp-2:
#       ansible_host: 192.168.11.115
#     k8s-cp-3:
#       ansible_host: 192.168.11.116

worker:
  hosts:
    k8s-wk-1:
      ansible_host: 192.168.11.124
    k8s-wk-2:
      ansible_host: 192.168.11.125
    k8s-wk-3:
      ansible_host: 192.168.11.126

control_plane:
  children:
    cp:
    cp_join:

all_node:
  children:
    control_plane:
    worker:
